# Generated by Django 5.2.1 on 2025-07-04 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admintareas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='due_date',
            new_name='dueDate',
        ),
    ]
